import { Driver, Menu, Rating, Restaurant, User } from "../types/seeddatatypes";

export const roles: string[] = ['Admin', 'Restaurant_Owner', 'User', 'Driver'];

export const permissions: string[] = ['Update', 'Delete', 'Create', 'View'];

export const features: string[] = [
    'Dashboard',
    'Home',
    'Cart',
    'Chat',
    'Profile',
    'Restaurant_Profile',
    'Menu',
    'User',
    'Order',
    'Restaurant',
    'Rating',
];

export const rolePermissions: {
    [index: string]: {
        [index: string]: string[];
    };
} = {
    User: {
        Home: ['View'],
        Dashboard: ['View'],
        Profile: ['View', 'Create', 'Update', 'Delete'],
        Cart: ['View', 'Create', 'Update', 'Delete'],
        Order: ['View'],
        Menu: ['View'],
        Rating: ['Create', 'Create'],
    },
    Restaurant_Owner: {
        Dashboard: ['View'],
        Profile: ['View', 'Create', 'Update', 'Delete'],
        Restaurant_Profile: ['View', 'Create', 'Update', 'Delete'],
        Chat: ['View', 'Create'],
        Menu: ['View', 'Create', 'Update', 'Delete'],
        Rating: ['View'],
    },
    Admin: {
        Dashboard: ['View'],
        Profile: ['View', 'Create', 'Update', 'Delete'],
        Chat: ['View', 'Create'],
        Menu: ['View', 'Create', 'Update', 'Delete'],
        User: ['View', 'Update', 'Delete'],
        Restaurant: ['View', 'Update', 'Delete'],
        Rating: ['View', 'Update', 'Delete'],
    },
};

export const usersdata: User[] = [
    {
        fname: "Puja",
        lname: "Moravadiya",
        email: "puja@gmail.com",
        phone: "9313003213",
        gender: "female",
        bd: new Date(2002 - 11 - 30),
        password: "$2y$07$xt1NeBAo.FsO7MSU2ZMoR.S6TYVay6HSoyo2pzE/fenCBJUTEg6VS",
        role_id: 1,
        city: "talala",
        state: "gujarat",
        street: "0,sasan road, kumbhani para",
        pincode: "362150",
    },
    {
        fname: "Maya",
        lname: "Vora",
        email: "maya@gmail.com",
        phone: "8974859632",
        gender: "female",
        bd: new Date(2003 - 12 - 15),
        password: "$2y$07$DEa8tVTNDaZp8hYOUODyj.qfMnEdDwrFt4Ec8QxAqqu.nK5BGXxE.",
        role_id: 2,
        city: "jungadh",
        state: "gujarat",
        street: "Mangnath Rd,",
        pincode: "362001",
    },
    {
        fname: "Aarav",
        lname: "Patel",
        email: "aarav@gmail.com",
        phone: "8745963258",
        gender: "male",
        bd: new Date(2002 - 6 - 5),
        password: "$2y$07$fJgexL.iM4lgVyJFk9BWdeRKj6FE7dDJCh1VVYpWZN6Er.t8UWmAu",
        role_id: 2,
        city: "Himatnagar",
        state: "gujarat",
        street: "Alkapuri Pologround, Alkapuri",
        pincode: "383001",
    },
    {
        fname: "Khushi",
        lname: "mehra",
        email: "khushi@gmail.com",
        phone: "7969854896",
        gender: "female",
        bd: new Date(2002 - 5 - 13),
        password: "$2y$07$Uy8tKFL6o6M6wj86Y2IE2e0jpqk4BkUuDYAG2WSIv3z9KcajKTEaG",
        role_id: 2,
        city: "Ahmedabad",
        state: "gujarat",
        street: "Sunrise Park Rd, Gurukul",
        pincode: "380052",
    },
    {
        fname: "Koushtubh",
        lname: "Acharya",
        email: "koushtubh@gmail.com",
        phone: "7930115555",
        gender: "male",
        bd: new Date(2003 - 5 - 12),
        password: "Dev@123",
        role_id: 2,
        city: "Ahmedabad",
        state: "gujarat",
        street: "Lal Darwaja",
        pincode: "380001",
    },
    {
        fname: "Manish",
        lname: "Dey",
        email: "manish@gmail.com",
        phone: "7922774647",
        gender: "male",
        bd: new Date(2003 - 5 - 12),
        password: "Devv@123",
        role_id: 2,
        city: "Vadodara",
        state: "gujarat",
        street: "Swaminarayan Mandir Rd, Badri Mohalla, Moghul Wada",
        pincode: "390017",
    },
    {
        fname: "Saurabh",
        lname: "Kalla",
        email: "saurabh@gmail.com",
        phone: "9313003213",
        gender: "male",
        bd: new Date(2003 - 5 - 12),
        password: "$2a$07$UMd4F6gPDHJISNE8MEWC4.TmobGJmii/ero7dKybC.dLno9ZwNXny",
        role_id: 3,
        city: "Ahmedabad",
        state: "gujarat",
        street: "1/2 Gitanjali Complex, Navrangpura",
        pincode: "380013",
    },
    {
        fname: "Srinivasan",
        lname: "Choudhry",
        email: "srinivasan@gmail.com",
        phone: "7922862591",
        gender: "male",
        bd: new Date(2003 - 5 - 12),
        password: "$2a$07$pYudgI1zCDmlHizeTlvEzO82uOkDnJDdGXyCsjJfJsQDWoZ/Bt5Z2",
        role_id: 4,
        city: "Surat",
        state: "gujarat",
        street: "Adajan Gam",
        pincode: "395009",
    },
    {
        fname: "Yogesh",
        lname: "Verma",
        email: "yogesh@gmail.com",
        phone: "9925243337",
        gender: "male",
        bd: new Date(2003 - 5 - 12),
        password: "Dev@1236",
        role_id: 3,
        city: "Ahmedabad",
        state: "gujarat",
        street: "Airport Cir",
        pincode: "382475",
    },
]

export const restaurantdata: Restaurant[] = [{
    name: "SpiceCraft",
    user_id: 2,
    address: "1/2 Gitanjali Complex, Navrangpura,Ahmedabad,Gujarat,380013",
    phone: "8974859623",
    image: "uploads/image-1721393617657-643010505-res1.jpeg",
},
{
    name: "Ascent: Alpine-Style Cuisine",
    user_id: 3,
    address: "Bombay Conductor Rd, Phase I, GIDC Vatwa,Ahmedabad,Gujarat,382445",
    phone: "7896584120",
    image: "uploads/image-1721393638532-667782212-res2.jpg",
},
{
    name: "Red Stiletto Restaurant",
    user_id: 4,
    address: "Swami Vivekananda Rd, Raikhad,Ahmedabad,Gujarat,380001",
    phone: "9965874521",
    image: "uploads/image-1721393653272-190403610-res3.jpg",
},
{
    name: "The Winstonian",
    user_id: 5,
    address: "GIDC Kabilpore,Navsari,Gujarat,396427",
    phone: "8974521596",
    image: "uploads/image-1721393668525-953404359-res4.jpg",
},
{
    name: "The Nouveau Table",
    user_id: 6,
    address: "Ganesh Circle, Mangalpura,Anand,Gujarat,388001",
    phone: "7979854628",
    image: "uploads/image-1721393692147-422516782-res55.jpeg",
},]


export const menudata: Menu[] = [{
    restaurant_id: 1,
    item_name: "italian pizza",
    price: 150,
    image: "uploads/image-1721394051818-850304740-italian.jpg",
},
{
    restaurant_id: 1,
    item_name: "sandwich",
    price: 120,
    image: "uploads/image-1721394082834-695463509-sandwitch.jpg",
},
{
    restaurant_id: 1,
    item_name: "french fries",
    price: 70,
    image: "uploads/image-1721394094453-367136742-french_fries.jpeg",
},
{
    restaurant_id: 2,
    item_name: "manchurian",
    price: 100,
    image: "uploads/image-1721394281317-314881175-manchurian.jpeg",
},
{
    restaurant_id: 2,
    item_name: "chowmein",
    price: 80,
    image: "uploads/image-1721394292716-313256665-chowmein.jpg",
},
{
    restaurant_id: 2,
    item_name: "fried rice",
    price: 120,
    image: "uploads/image-1721394303518-272835406-fried_rice.jpg",
},
{
    restaurant_id: 3,
    item_name: "chilli paneer",
    price: 120,
    image: "uploads/image-1721394324538-380055601-chilli_panner.jpeg",
},
{
    restaurant_id: 3,
    item_name: "garlic bread",
    price: 256,
    image: "uploads/image-1721394334601-783004394-garlic_bread.jpg",
},
{
    restaurant_id: 3,
    item_name: "fixed punjabi thali",
    price: 250,
    image: "uploads/image-1721394349179-862086351-fixed_punjabi_thali.jpeg",
},
{
    restaurant_id: 4,
    item_name: "veg hot & sour soup",
    price: 80,
    image: "uploads/image-1721394362679-425507601-hot-and-sour-soup.jpg",
},
{
    restaurant_id: 4,
    item_name: "paneer roll",
    price: 130,
    image: "uploads/image-1721394378993-162379098-panner_roll.jpg",
},
{
    restaurant_id: 4,
    item_name: "vge momos",
    price: 70,
    image: "uploads/image-1721394418678-643576727-veg_momos.jpg",
},
{
    restaurant_id: 5,
    item_name: "burger",
    price: 100,
    image: "uploads/image-1721394432922-307305546-burger.jpg",
},
{
    restaurant_id: 5,
    item_name: "vadapaw",
    price: 50,
    image: "uploads/image-1721394462666-92334847-vadapaw.jpeg",
},]


export const driverdata: Driver[] = [{
    user_id: 7,
},
{
    user_id: 9,
},
]

export const ratingdata: Rating[] = [
    {
        user_id: 1,
        menu_id: 1,
        content: "nice",
        rating: 4.2,
    },
    {
        user_id: 1,
        menu_id: 2,
        content: "nice",
        rating: 3.8,
    },
    {
        user_id: 1,
        menu_id: 3,
        content: "nice",
        rating: 3.2,
    },
    {
        user_id: 1,
        menu_id: 4,
        content: "nice",
        rating: 4.8,
    },
    {
        user_id: 2,
        menu_id: 1,
        content: "nice",
        rating: 2.8,
    },
    {
        user_id: 2,
        menu_id: 2,
        content: "nice",
        rating: 3.6,
    },
    {
        user_id: 2,
        menu_id: 3,
        content: "nice",
        rating: 4.5,
    },
    {
        user_id: 2,
        menu_id: 4,
        content: "nice",
        rating: 1.6,
    },
    {
        user_id: 3,
        menu_id: 1,
        content: "nice",
        rating: 5,
    },
    {
        user_id: 3,
        menu_id: 2,
        content: "nice",
        rating: 3.3,
    },
    {
        user_id: 3,
        menu_id: 3,
        content: "totally unworth to order",
        rating: 2.4,
    },
    {
        user_id: 3,
        menu_id: 4,
        content: "nice",
        rating: 2.9,
    },
    {
        user_id: 4,
        menu_id: 1,
        content: "nice",
        rating: 3.7,
    },
    {
        user_id: 4,
        menu_id: 2,
        content: "nice",
        rating: 4.8,
    },
    {
        user_id: 4,
        menu_id: 3,
        content: "nice",
        rating: 2.5,
    },
    {
        user_id: 4,
        menu_id: 4,
        content: "nice",
        rating: 3.8,
    },
]